### PR TITLE
Fix assignment

### PR DESCRIPTION
**Pull request by apple-x-co**
### Qiq template

```
{{ /** @var Qiq\Engine&Qiq\Helper\Html\HtmlHelpers $this */ }}
{{= anchor ('https://qiqphp.com', 'Qiq Project') }}
{{ $a = anchor ('https://qiqphp.com', 'Qiq Project') }}
```

### Compiled (now)

```
<?php /** @var Qiq\Engine&Qiq\Helper\Html\HtmlHelpers $this */ ?>
<?= $this->anchor ('https://qiqphp.com', 'Qiq Project') ?><?= PHP_EOL ?>
<?php $a = anchor ('https://qiqphp.com', 'Qiq Project') ?>
```

### Expectations

```
<?php /** @var Qiq\Engine&Qiq\Helper\Html\HtmlHelpers $this */ ?>
<?= $this->anchor ('https://qiqphp.com', 'Qiq Project') ?><?= PHP_EOL ?>
<?php $a = $this->anchor ('https://qiqphp.com', 'Qiq Project') ?>
```

👉 `$a = $this->anchor`

### CODE REVIEW

**Comment by pmjones** [comment]
Currently, the exhibited behavior is correct. That is, using an opening keyword `{{= anchor ( ... ) }}` gets converted to `$this->anchor(...)`, whereas  anything that is *not* an opening keyword will *not* get converted.

Having said that, I do not really like that behavior too much. Until now I have not found a way to fix it.

But this PR has motivated me, and I believe I may have a fix that uses `token_get_all()` to discover function calls and then convert them to `$this->` method calls.

I will report back as I experiment further, and thanks for your patience.

**Comment by apple-x-co** [comment]
Thank you very much!!
I'm looking forward to it.

**Comment by pmjones** [comment]
@apple-x-co Please try out the new branch [2.x-php-tokenizer](https://github.com/qiqphp/qiq/tree/2.x-php-tokenizer) and see if it works the way you think it should.

**Comment by apple-x-co** [comment]
Thank you very much! !
It's now working as I expected 🚀
Existing templates are also working.

---

## Check result

```bash
composer require qiq/qiq:"dev-2.x-php-tokenizer"
```

### Case1

qiq
```text
{{ if (isAllowed('settings', 'read')): }}
<p><a href="settings/">Settings</a></p>
{{ endif }}
```

php (compiled)
```php
<?php $this->setIndent("\n") ?><?php if ($this->isAllowed('settings', 'read')): ?>
<p><a href="settings/">Settings</a></p>
<?php $this->setIndent("\n") ?><?php endif ?>
```

### Case2

qiq
```text
{{ if ($message = flashMessage()): }}
{{= render('partials/Admin/AlertInformation', ['text' => $message]) }}
{{ endif }}
```

php (compiled)
```php
<?php if ($message = $this->flashMessage()): ?>
<?= $this->render('partials/Admin/AlertInformation', ['text' => $message]) ?><?= PHP_EOL ?>
<?php endif ?>
```

**Comment by pmjones** [comment]
Wow that is great news -- I will merge to master, test a bit more, and release.

Thank you for the motivation on this!

**Comment by apple-x-co** [comment]
I'm happy that Qiq is powered up.
May I close this PR?

**Comment by pmjones** [comment]
@apple-x-co Yes, please do. Thanks again!

**Pull request closed without merging**
