### PR TITLE
Add Twig-like inheritance functionality

### PR DESCRIPTION
**Pull request by pmjones**
This PR adds an `extends()` feature that mimics a similar feature in Twig.

@harikt @koriym and others, please let me know your comments/concerns/questions.

@koriym This PR adds one documentation page that will need translating at some point.

Thanks all!

### CODE REVIEW

**Comment by pmjones** [comment]
@harikt @koriym and all: I just realized this may not operate as intended. I'll have to work on it some more; the docs may change as a result. @koriym you can hold off translation until further notice. Sorry for the noise, everyone.

**Comment by koriym** [comment]
@pmjones No problem

**Comment by harikt** [comment]
There is a question here : What will happen to a section if it is defined in any of the parent layout, but missing in others.

[tests/templates/ext/layout-1.php]

```
Layout 1 Content
{{= getSection ('bar') }}
{{= getContent() }}
{{= getSection('foo') }}
```

[tests/templates/ext/view-1.php]

```
{{ extends ('./layout-1') }}
{{ prependSection ('bar') }}
Bar 1 View
{{ endSection ('bar') }}
View 1 Content
```

[tests/templates/ext/view-2.php]

```
{{ extends ('./view-1') }}
{{ prependSection ('foo') }}
Foo 1 View
{{ endSection ('foo') }}
View 2 Content
```

[tests/templates/ext/view-3.php]

```
{{ extends ('./view-2') }}
{{ prependSection ('foo') }}
Foo 2 View
{{ endSection ('foo') }}
View 3 Content 
```

Does rendering view-3 will render section bar contents inside layout-1 or no ?

**Comment by pmjones** [comment]
@harikt @koriym and all, I had to go "back to formula" on this, as the "sections" implementation would not handle this properly after all.

Instead, I have introduced an additional "blocks" implementation that mimics Twig behavior more closely. Please take a look at your convenience.

@koriym I have updated the `inheritance.md` documentation accordingly, but I am not really satisfied with it yet; I'll let you know when it's really done and ready for translation.

@harikt you asked under the original "sections" implementation:

> What will happen to a section if it is defined in any of the parent layout, but missing in others.

If you `getSection('foo')`  and 'foo' is not a defined section, you get `null` from it; echoing that gets you a blank string. So  no error is raised if you get a section that does not exists.

Under the new "blocks" implementation, calling `getSection()` without having called a corresponding `setSection()` should net you an error related to output buffering. Let me know what you think of that.

Thanks for your patience, everyone!

**Comment by harikt** [comment]
@pmjones In the example I mentioned regarding sections : https://github.com/qiqphp/qiq/pull/16#issuecomment-1418334552

I was expecting 

```
Layout 1 Content
Bar 1 View
View 1 Content
View 2 Content
View 3 Content
Foo 2 View
```

But it looks this may end up in 

```
Layout 1 Content
View 1 Content
Foo 2 View
```

I will come back again and comment on the latest block implementation. Give me some time.

Thanks

**Comment by koriym** [comment]
> will need translating at some point.

Is now the time?

**Comment by pmjones** [comment]
@koriym I decided yesterday that this needs to become a 2.x branch, since it will be a major BC break. Further, there should be only one docs folder, with docs/en and docs/ja. Finally, the docs in this branch for inheritance and blocks needs to be redone, with blocks on its own page and extends() on another page.

To sum up: not yet. I will finalize docs/en in a 2.x branch, with the smallest diffs that I can, and then present those for translation. I apologize for the delay.

**Comment by koriym** [comment]
@pmjones Noted. Thanks for good work!

**Comment by pmjones** [comment]
@harikt @koriym All right, I think this branch is **not** a BC break after all. I should be able to release it as a new 1.x version; the 2.x version will incorporate these changes and others.

@koriym Your team can have a go at translating the changes (and new docs files) in this branch whenever you are ready.

Thank you all for your patience!

**Comment by pmjones** [comment]
@koriym Do you mind if I make a new 1.x release without the new doc translations? I'd like to release 1.x so that I can base 2.x on it, and make at least a beta release of 2.x in the next week or so. (We can add the doc translations later easily enough.)

**Comment by koriym** [comment]
No problem, Go ahead!

**Pull request merged**
